name: 图片空间插件
identification: notadd/ext-mall-gallery
description: 图片空间管理插件
author:
    - Hollydan
    - 2642956839@qq.com
version: 0.1.0
provider: Notadd\MallGallery\Extension
assets:
    administration:
        notadd/mall-gallery:
            permissions:
            scripts: assets/extensions/notadd/mall-gallery/js/addon.min.js
            stylesheets: assets/extensions/notadd/mall-gallery/css/addon.min.css
csrf:
    - 'api/mall_gallery*'
events:
    subscribes:
        - Notadd\MallGallery\Listeners\RouteRegister
migrations:
    - databases/migrations
publishes:
    assets/extensions/notadd/mall-gallery: resources/mixes/administration/dist/assets/extensions/notadd/mall-gallery
